import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { packageKey, type DependencyNode } from '../types/index';
import { NpmAdapter } from './npm-adapter';

const tmpDirs: string[] = [];
afterEach(async () => {
  await Promise.all(tmpDirs.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});

async function writeProject(files: Record<string, string>): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), 'venom-pm-'));
  tmpDirs.push(dir);
  for (const [name, content] of Object.entries(files)) await writeFile(join(dir, name), content);
  return dir;
}

function byKey(nodes: DependencyNode[]): Map<string, DependencyNode> {
  return new Map(nodes.map((n) => [packageKey(n.ref), n]));
}

const PACKAGE_JSON = JSON.stringify({
  name: 'demo',
  version: '1.0.0',
  dependencies: { a: '^1.0.0' },
  devDependencies: { d: '^2.0.0' },
});

describe('NpmAdapter — pnpm-lock.yaml (v9)', () => {
  it('resolves versions, edges, depth, and scopes', async () => {
    const dir = await writeProject({
      'package.json': PACKAGE_JSON,
      'pnpm-lock.yaml': [
        "lockfileVersion: '9.0'",
        'importers:',
        '  .:',
        '    dependencies:',
        '      a:',
        '        specifier: ^1.0.0',
        '        version: 1.0.0',
        '    devDependencies:',
        '      d:',
        '        specifier: ^2.0.0',
        '        version: 2.0.0',
        'packages:',
        '  a@1.0.0:',
        '    resolution: {integrity: sha1}',
        '  b@3.0.0:',
        '    resolution: {integrity: sha2}',
        '  d@2.0.0:',
        '    resolution: {integrity: sha3}',
        'snapshots:',
        '  a@1.0.0:',
        '    dependencies:',
        '      b: 3.0.0',
        '  b@3.0.0: {}',
        '  d@2.0.0: {}',
        '',
      ].join('\n'),
    });

    const result = await new NpmAdapter().parseProject(dir);
    expect(result!.root).toMatchObject({ name: 'demo', version: '1.0.0' });
    const nodes = byKey(result!.nodes);
    expect(nodes.get('npm:a@1.0.0')).toMatchObject({
      direct: true,
      depth: 1,
      scopes: ['production'],
    });
    expect(nodes.get('npm:a@1.0.0')!.dependencies).toEqual(['npm:b@3.0.0']);
    expect(nodes.get('npm:b@3.0.0')).toMatchObject({ direct: false, depth: 2 });
    expect(nodes.get('npm:d@2.0.0')).toMatchObject({
      direct: true,
      depth: 1,
      scopes: ['development'],
    });
  });
});

describe('NpmAdapter — yarn.lock (classic v1)', () => {
  it('resolves versions, edges, depth, and scopes from the manifest', async () => {
    const dir = await writeProject({
      'package.json': PACKAGE_JSON,
      'yarn.lock': [
        '# THIS IS AN AUTOGENERATED FILE',
        '# yarn lockfile v1',
        '',
        'a@^1.0.0:',
        '  version "1.0.0"',
        '  resolved "https://registry.yarnpkg.com/a/-/a-1.0.0.tgz"',
        '  dependencies:',
        '    b "^3.0.0"',
        '',
        'b@^3.0.0:',
        '  version "3.0.0"',
        '  resolved "https://registry.yarnpkg.com/b/-/b-3.0.0.tgz"',
        '',
        'd@^2.0.0:',
        '  version "2.0.0"',
        '  resolved "https://registry.yarnpkg.com/d/-/d-2.0.0.tgz"',
        '',
      ].join('\n'),
    });

    const result = await new NpmAdapter().parseProject(dir);
    const nodes = byKey(result!.nodes);
    expect(nodes.get('npm:a@1.0.0')).toMatchObject({
      direct: true,
      depth: 1,
      scopes: ['production'],
    });
    expect(nodes.get('npm:a@1.0.0')!.dependencies).toEqual(['npm:b@3.0.0']);
    expect(nodes.get('npm:b@3.0.0')).toMatchObject({ direct: false, depth: 2 });
    expect(nodes.get('npm:d@2.0.0')).toMatchObject({
      direct: true,
      depth: 1,
      scopes: ['development'],
    });
  });
});
